### ISSUE TITLE
All text is displayed as black

### ISSUE THREAD

**Issue by TheDrB0B** [sprince0031/PitchBlack-UserStyle-themes#11]
All text is displayed as black so you can't really see anything other than the song you're selecting :(

Thanks for doing this man, I use Apple Music a lot and it would be lovely to get it in dark mode and I think your style is the only one out there!

**Comment by TheDrB0B** [comment]
![2024-02-26 10_40_56-Window](https://github.com/sprince0031/PitchBlack-UserStyle-themes/assets/161356692/91ea5e25-3caf-4517-b5f3-0c9ea4d9b04c)

**Comment by sprince0031** [comment]
Thank you so much for trying out my theme and for your feedback! I really appreciate it. 😄 

Apple Music does have a dark theme where the text colour is changed to a lighter colour. However, there is no direct toggle on their website to enable it. Your system theme has to be dark for it to be enabled. So, how I intended it was that users would have their default dark mode toggled already and then would apply this theme over that (because frankly, their default dark theme sucks XD. Talk about it being lightish grey. The real dark mode is the AMOLED kind of dark mode in my opinion XD). I've attached a screen recording of how it works for me where it changes when I switch between light and dark modes in my OS's theme settings.

[apple-music-dark-mode-bug-demo.webm](https://github.com/sprince0031/PitchBlack-UserStyle-themes/assets/19924682/5e71135e-f82a-4a77-9851-f72660821939)

However, I do see why this might not be directly apparent. I can make a change where I enable the dark mode's default font colour directly regardless of the system theme settings since you're probably using my theme for the (real) dark mode anyway (though technically you can change the background to a light colour and still keep a customised light theme if that's your taste with this theme). Let me see what I can do to more intuitively address this and I'll post an update. In the meanwhile, try toggling your system wide theme to dark to work around this issue.

Cheers!

**Comment by TheDrB0B** [comment]
Awesome! Thanks for sharing, I got it working finally! Had to change my device's theme which actually makes everything much better. Apple Music definetively looks awesome with you style, thank you so much!!
